[versions]
binaryCompat = "0.13.2"
configuration = "0.1.5"
encoding = "2.0.0"
endians = "0.1.0"
gradleVersions = "0.50.0"
kotlin = "1.9.20"
publish = "0.25.3"

[libraries]
gradle-kmp-configuration = { module = "io.matthewnelson:gradle-kmp-configuration-plugin", version.ref = "configuration" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }

# Tests
encoding-base16 = { module = "io.matthewnelson.encoding:base16", version.ref = "encoding" }
endians-endians = { module = "org.kotlincrypto.endians:endians", version.ref = "endians" }

[plugins]
binaryCompat = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompat" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersions" }
